# The deployment section should be excluded until
# it is explicitly included in module 5
version: 2
jobs:
  test:
    steps:
      - mocha
  deployment:
    steps:
      dockerhub:
        branch: master
        commands:
          - $DOCKER_HUB_TRIGGER

