# The deployment section should be excluded until
# it is explicitly included in module 5
version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    steps:
      - mocha
  deployment:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    steps:
      dockerhub:
        branch: master
        commands:
          - $DOCKER_HUB_TRIGGER
